# Generated by Django 3.0.6 on 2020-06-04 11:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('sidoNm', models.CharField(max_length=400)),
                ('sgguNm', models.CharField(max_length=400)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('yadmNm', models.CharField(max_length=200)),
                ('hospTyTpCd', models.CharField(blank=True, max_length=2, null=True)),
                ('telno', models.CharField(max_length=30)),
                ('adtFrDd', models.CharField(max_length=8)),
                ('spclAdmTyCd', models.CharField(max_length=2)),
            ],
        ),
    ]
