# Generated by Django 3.0.6 on 2020-06-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200604_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='hospTyTpCd',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='isInspect',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='isReliefhos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='isTriage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
