# Generated by Django 3.0.6 on 2020-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('seq', models.IntegerField()),
                ('create_dt', models.CharField(max_length=30)),
                ('death_cnt', models.IntegerField()),
                ('defCnt', models.IntegerField()),
                ('gubun', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gubun_cn', models.CharField(max_length=30)),
                ('gubun_en', models.CharField(max_length=30)),
                ('inc_dec', models.IntegerField()),
                ('isol_clear_cnt', models.IntegerField()),
                ('isollingCnt', models.IntegerField()),
                ('localOccCnt', models.IntegerField()),
                ('overFlowCnt', models.IntegerField()),
                ('qur_rate', models.FloatField()),
                ('std_day', models.CharField(max_length=30)),
            ],
        ),
    ]
